### ISSUE TITLE
Failure to Install git-credential-manager-core on macOs

### ISSUE THREAD

**Issue by cts3njitedu** [GitCredentialManager/git-credential-manager#1121] opened 2023-02-20 18:41 UTC
Seeing this exception after running 
brew install --cask git-credential-manager-core

Error: Failure while executing; `/usr/bin/sudo -E LOGNAME=<username> USER=<username> USERNAME=<username> -- /usr/sbin/installer -pkg /usr/local/Caskroom/git-credential-manager-core/2.0.886/gcm-osx-x64-2.0.886.pkg -target / -allowUntrusted` exited with 1. Here's the output:
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.886.pkg”.)

**Comment by ldennington** [comment] 2023-02-21 17:49
Closing as duplicate of #1035

**Closed by ldennington** 2023-02-21 17:49 UTC
