### ISSUE TITLE
fatal: The SSL connection could not be established

### ISSUE THREAD

**Issue by frednunesjr** [GitCredentialManager/git-credential-manager#473] opened 2021-10-02 18:54 UTC
**Which version of GCM Core are you using?**

2.0.498+7ad55fb809 on Linux Mint 20.2 (Ubuntu)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

When I try to git pull on the Auth step I get these error:

Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 1
info: please complete authentication in your browser...
fatal: The SSL connection could not be established, see inner exception.
fatal: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

**Comment by mjcheetham** [comment] 2021-10-05 13:34
> ```
> fatal: The SSL connection could not be established, see inner exception.
> fatal: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
> ```

Are you running behind a web proxy of any sorts, or behind a VPN? GCM is failing because it cannot establish a secure TLS (SSL) connection to the remote, and the problem is an untrusted root certificate.

**Comment by frednunesjr** [comment] 2021-10-05 18:05
> > ```
> > fatal: The SSL connection could not be established, see inner exception.
> > fatal: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
> > ```
> 
> Are you running behind a web proxy of any sorts, or behind a VPN? GCM is failing because it cannot establish a secure TLS (SSL) connection to the remote, and the problem is an untrusted root certificate.

Nope, I'm not. Since GitHub doesn't allow to access via HTTPS a few months, I've been using GCM, but I tried to login using another method GitHub CLI and logged in normally.

It's started to happen after I downgraded my OpenSSL - trying to connect Azure Data Studio with my SQL Server DB which was successfully - that wasn't in the upgraded at all, but I already upgraded to last version too and nothing happens.

**Comment by mjcheetham** [comment] 2021-11-17 13:24
When you visit `github.com` in a web browser, what does the certificate chain look like? You can usually find this by clicking the HTTPS "padlock" icon.

**Comment by frednunesjr** [comment] 2021-11-18 03:30
> When you visit `github.com` in a web browser, what does the certificate chain look like? You can usually find this by clicking the HTTPS "padlock" icon.

First when I choose option 1 - Web Browser - it was opened a localhost window (it's a normal thing, everytime it was like it, just that after upgrading OpenSSL to 1.1.1l this kind of thing started).

Localhost, unsecured.

**Comment by mjcheetham** [comment] 2022-03-01 14:19
It's possible there was some certificate caching error that has been resolved. Closing - please reopen or create a new issue if this has not been fixed.

**Closed by mjcheetham** 2022-03-01 14:19 UTC
Labels: auth-issue
