### ISSUE TITLE
diagnose crashes when trying to access libsecret

### ISSUE THREAD

**Issue by Skycoder42** [GitCredentialManager/git-credential-manager#888] opened 2022-10-06 17:09 UTC
**Which version of GCM are you using?**

```
2.0.785+6074e4e3d3
```

**Expected behavior**

The diagnose command is successful for all steps

**Actual behavior**

The diagnose command crashes with signal 6 when checking the libsecret integration

**Logs**

```
$ git credential-manager-core diagnose -o /tmp/gcm-diagnose.log

18:55:19.095743 git.c:749               trace: exec: git-credential-manager-core diagnose -o /tmp/gcm-diagnose.log
18:55:19.095882 run-command.c:654       trace: run_command: git-credential-manager-core diagnose -o /tmp/gcm-diagnose.log
18:55:19.257310 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
18:55:19.263791 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
18:55:19.263821 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
18:55:19.263833 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux manjomen 5.19.13-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct 4 14:48:49 UTC 2022 x86_64 GNU/Linux
18:55:19.263927 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/share/git-credential-manager-core/git-credential-manager-core
18:55:19.263968 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: diagnose -o /tmp/gcm-diagnose.log
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
  >>>>  Networking18:55:20.282321 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
[ OK ] Networking
 [ OK ] Git
  >>>>  Credential storagegit-credential-manager-core: ../libsecret/egg/egg-secure-memory.c:596: sec_free: Assertion `cell->requested > 0' failed.
error: git-credential-manager-core died of signal 6
```

I also attached the full logs as generated by the command. However, as the diagnose step for libsecret crashes, those logs are not beeing generated: [gcm-diagnose.zip](https://github.com/GitCredentialManager/git-credential-manager/files/9726993/gcm-diagnose.zip)

Also, here are some more infos regarding my system that might be relevant:
- OS: `Linux 5.19.13-1-MANJARO x86_64 22.0.0 Sikaris`
- git version: `git version 2.37.3`
- secret service implementation: `kwalletmanager5 22.08.1`

**Comment by ldennington** [comment] 2022-10-06 23:59
This appears to be a duplicate of #793, closing in favor of that issue.

**Closed by ldennington** 2022-10-06 23:59 UTC
Labels: platform:linux, auth-issue
