### ISSUE TITLE
Build on linux-arm64 produces linux-x64 binaries

### ISSUE THREAD

**Issue by avoidik** [GitCredentialManager/git-credential-manager#947] opened 2022-11-04 21:37 UTC
Hello,

Build on linux-arm64 produces linux-x64 binaries even when `--arch arm64 --os linux` flags were set. How can I fix it?

**Comment by ldennington** [comment] 2022-11-07 18:25
Can you please include the full command you're using to build?

**Comment by mjcheetham** [comment] 2022-11-07 23:27
> `--arch arm64 --os linux`

I don't recognise those build arguments.. they aren't `dotnet` command arguments.

**Comment by avoidik** [comment] 2022-11-08 03:16
Here is the comman

```bash
sudo dotnet build ./src/linux/Packaging.Linux/Packaging.Linux.csproj -c Release -p:InstallFromSource=true --arch arm64 --os linux
```

Here is the reference to extra params

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build

**Comment by rowntreerob** [comment] 2022-11-09 00:27
+1 on the arm64 for Linux    

   new chromebook thats  good dev box,  but no gpg support for pushing signed commits to git

**Comment by jozefizso** [comment] 2022-11-10 20:00
This will be helpful for WSL on Windows ARM systems.

**Comment by grzn** [comment] 2022-11-28 09:39
+1

**Comment by ldennington** [comment] 2023-02-27 22:38
Duplicate of #606

**Closed by ldennington** 2023-02-27 22:38 UTC
