### ISSUE TITLE
How to verify Debian package signature?

### ISSUE THREAD

**Issue by hickford** [GitCredentialManager/git-credential-manager#809] opened 2022-07-27 11:59 UTC
According to https://github.com/GitCredentialManager/git-credential-manager/blob/80423faa16fc23532306b10c5b69c926708734e8/.github/workflows/release.yml#L397 the Debian package is signed with "ESRP client" whatever that is (I couldn't find any docs). How can a Debian user verify this signature?

I tried `dpkg-sig --verify` with key https://packages.microsoft.com/keys/microsoft.asc (imported with `gpg --import microsoft.asc`) but got an error:

```
> dpkg-sig --verify gcm-linux_amd64.2.0.785.deb
Processing gcm-linux_amd64.2.0.785.deb...
BADSIG _gpgorigin
```

**Comment by mjcheetham** [comment] 2022-07-27 13:24
Hmm... I've just tried downloading the latest package and verify it, and get this:

```console
$ dpkg-sig --verify ./gcm-linux_amd64.2.0.785.deb 
Processing ./gcm-linux_amd64.2.0.785.deb...
UNKNOWNSIG _gpgorigin BE1229CF
```

Note that, according to the documents [here](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#package-and-repository-signing-key) the signature of the public Microsoft signing key (since we are still using the Microsoft code-signing process) is `BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF`.

**Comment by hickford** [comment] 2022-07-27 19:15
BE1229CF is indeed https://packages.microsoft.com/keys/microsoft.asc ; you can import the key with `gpg --import microsoft.asc`

The problem isn't specific to GCM -- I can reproduce with dotnet packages from packages.microsoft.com (eg. [dotnet-runtime-6.0.7-x64.deb](https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-runtime-6.0/dotnet-runtime-6.0.7-x64.deb)). Interestingly the *rpm* packages (eg. [https://packages.microsoft.com/fedora/36/prod/dotnet-runtime-6.0.7-x64.rpm](https://packages.microsoft.com/fedora/36/prod/dotnet-runtime-6.0.7-x64.rpm)) verify without problem `rpm --import microsoft.asc; rpm -K dotnet-runtime-6.0.7-x64.rpm`.

**Comment by hickford** [comment] 2022-07-27 19:17
Some context about deb package signing https://askubuntu.com/a/677645

> Package signing on Ubuntu/Debian systems is rather messy. ... In order to sign a package, you can use either: debsigs or dpkg-sig. The signatures are not compatible with one another, so you'll need to make sure the user is using the proper tool on the receiving side for verifying signatures. dpkg-sig is easier to use for both you and the user, but debsigs is the tool with built-in support (which is disabled by default) on Ubuntu and Debian.

**Comment by skitt** [comment] 2022-07-28 12:54
The packages contain a `dpkg-sig` signature, not a `debsigs` signature — extracting the signature using `debsig-verify` doesn’t produce valid OpenPGP data.

**Comment by ldennington** [comment] 2022-07-28 19:49
I spoke with the packages.microsoft.com maintainers, and they confirmed that ESRP’s signatures are incompatible with `dpkg-sig`. As @skitt pointed out, they _are_ compatible with `debsig-verify`, though. See below for steps to setup and use  of `debsig-verify`.

```
apt-get install -y debsig-verify
wget https://packages.microsoft.com/keys/microsoft.asc
gpg --output microsoft.gpg --dearmor microsoft.asc
# Note that the fingerprint of this key is "EB3E94ADBE1229CF", which you can determine by doing:
# gpg --show-keys microsoft.asc | head -n 2 | tail -n 1 | tail -c 17
 
# Copy dearmored public key to debsig keyring folder
mkdir /usr/share/debsig/keyrings/EB3E94ADBE1229CF
mv microsoft.gpg /usr/share/debsig/keyrings/EB3E94ADBE1229CF/
 
# Create an appropriate policy file
mkdir /etc/debsig/policies/EB3E94ADBE1229CF
cat > /etc/debsig/policies/EB3E94ADBE1229CF/generic.pol << EOL
<?xml version="1.0"?>
<!DOCTYPE Policy SYSTEM "https://www.debian.org/debsig/1.0/policy.dtd">
<Policy xmlns="https://www.debian.org/debsig/1.0/">

  <!-- Here name and description can be anything. -->
  <Origin Name="Microsoft" id="EB3E94ADBE1229CF" Description="[gpgsecurity@microsoft.com](mailto:gpgsecurity@microsoft.com)"/>

  <Selection>
    <Required Type="origin" File="microsoft.gpg" id="EB3E94ADBE1229CF"/>
  </Selection>

  <Verification MinOptional="0">
    <Required Type="origin" File="microsoft.gpg" id="EB3E94ADBE1229CF"/>
  </Verification>

</Policy>
EOL

# Now download deb and verify it.
wget https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.785/gcm-linux_amd64.2.0.785.deb
debsig-verify gcm-linux_amd64.2.0.785.deb 
> debsig: Verified package from 'gpgsecurity@microsoft.com' (Microsoft)
```

Closing accordingly.

**Closed by ldennington** 2022-07-28 19:49 UTC
Labels: auth-issue
