### ISSUE TITLE
Using too much CPU

### ISSUE THREAD

**Issue by ekwoka** [GitCredentialManager/git-credential-manager#1140] opened 2023-03-06 12:07 UTC
![Screenshot 2023-03-06 at 4 06 24 PM](https://user-images.githubusercontent.com/43540491/223105985-5746287c-a629-4ebc-94b4-c8f3577c6ca2.png)

Mac OS latest
git-credential-manager latest

It's just running hot and driving up the whole system temp like 10 degrees (normally it's quite cool)

**Comment by ldennington** [comment] 2023-03-07 20:53
Closing, as it's a duplicate of #939

**Closed by ldennington** 2023-03-07 20:53 UTC

**Comment by ekwoka** [comment] 2023-03-08 02:48
@ldennington I don't think this is the same cause.

The behavior is quite different and it's only present in the latest version (I downgraded one version and it's back to normal)

**Comment by ldennington** [comment] 2023-03-13 22:16
Please fill out the [authentication issue template](https://aka.ms/gcm/bug), which includes the version you have installed, logs, etc. Until we have that information we cannot investigate.

**Comment by ekwoka** [comment] 2023-03-14 02:47
Okay, thank you. It was not at all clear that that was the template that made sense, as this is just something that it does regardless of any actual git activities.
