### ISSUE TITLE
Error installing 'gcm-osx-x64-2.0.886.pkg'

### ISSUE THREAD

**Issue by emeraldjava** [GitCredentialManager/git-credential-manager#1076] opened 2023-01-29 10:53 UTC
I get the following error when installing 'git-credential-manager-core' via this brew command. Any suggestions would be appreciated.

➜  ~ brew install --cask git-credential-manager-core -vvv

==> Downloading https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-osx-x64-2.0.886.pkg
Already downloaded: /Users/emeraldjava/Library/Caches/Homebrew/downloads/912da4d5214aa1b4cc1d9a6df532477217279ef639569a97d1547220e25eceec--gcm-osx-x64-2.0.886.pkg
==> Verifying checksum for cask 'git-credential-manager-core'

==> Installing Cask git-credential-manager-core
cp -p /Users/emeraldjava/Library/Caches/Homebrew/downloads/912da4d5214aa1b4cc1d9a6df532477217279ef639569a97d1547220e25eceec--gcm-osx-x64-2.0.886.pkg /usr/local/Caskroom/git-credential-manager-core/2.0.886/gcm-osx-x64-2.0.886.pkg

==> Running installer for git-credential-manager-core; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Git Credential Manager…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%9.277837
installer:PHASE:Writing files…
installer:%25.569053
installer:PHASE:Writing files…
installer:%62.265964
installer:PHASE:Moving items into place…
installer:%90.416919
installer:PHASE:Running package scripts…
installer:%91.771267
installer:PHASE:Running package scripts…
installer:%92.091518
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.886.pkg”.)

==> Purging files for version 2.0.886 of Cask git-credential-manager-core
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=emeraldjava USER=emeraldjava USERNAME=emeraldjava /usr/sbin/installer -pkg /usr/local/Caskroom/git-credential-manager-core/2.0.886/gcm-osx-x64-2.0.886.pkg -target / -verboseR -allowUntrusted` exited with 1. Here's the output:
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Git Credential Manager…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%9.277837
installer:PHASE:Writing files…
installer:%25.569053
installer:PHASE:Writing files…
installer:%62.265964
installer:PHASE:Moving items into place…
installer:%90.416919
installer:PHASE:Running package scripts…
installer:%91.771267
installer:PHASE:Running package scripts…
installer:%92.091518
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-x64-2.0.886.pkg”.)

**Comment by ldennington** [comment] 2023-01-29 23:58
This is a duplicate of #1035 - closing in favor of that issue.

**Closed by ldennington** 2023-01-29 23:58 UTC
