### ISSUE TITLE
Brew install (macOS) is hardwired to x64

### ISSUE THREAD

**Issue by sethrj** [GitCredentialManager/git-credential-manager#805] opened 2022-07-25 15:31 UTC
I'm trying to install GCM on my new MacBook Air (M2), but the version it tries to install requires Rosetta. Since an arm64 version is available through the GitHub releases page, the brew package recipe needs to be updated to account for `arm64` or `x86` based on the host architecture.

Error message:
```
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - Git Credential Manager can’t be installed on this computer.
==> Purging files for version 2.0.785 of Cask git-credential-manager-core
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=seth USER=seth USERNAME=seth /usr/sbin/installer -pkg /opt/homebrew/Caskroom/git-credential-manager-core/2.0.785/gcm-osx-x64-2.0.785.pkg -target / -allowUntrusted` exited with 1. Here's the output:
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - Git Credential Manager can’t be installed on this computer.
```

**Comment by ldennington** [comment] 2022-07-25 16:26
Closing, as this is a duplicate of #772

**Closed by ldennington** 2022-07-25 16:26 UTC

**Comment by sethrj** [comment] 2022-07-25 16:59
Sorry about the duplication! I did try to search for duplicates but clearly it wasn't comprehensive enough.
