### ISSUE TITLE
Homebrew: Installation failure

### ISSUE THREAD

**Issue by itskando** [GitCredentialManager/git-credential-manager#1132] opened 2023-02-27 20:41 UTC
### Version

N/A - fails to install

### Operating system

macOS

### OS version or distribution

13.2.1 (22D68)

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

No, for a different reason - please describe behavior below

### Expected behavior

I expected the following commands, as recommended in the [documentation](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git), to function:
```
kando@benvolio ~ % brew tap microsoft/git             
kando@benvolio ~ % brew install --cask git-credential-manager-core
```
[Homebrew's catalog](https://formulae.brew.sh/formula/git-credential-manager#default) states to use:
```
kando@benvolio ~ % brew install git-credential-manager-core
```
which also failed.

That page, the version is stable (with green checkmark),  
although next to the title, there is a red circle with a line through it — see attached image.

![Screenshot 2023-02-27 at 3 39 14 PM](https://user-images.githubusercontent.com/15063663/221680436-bd263a6a-da67-4edc-abab-8bbdeaec27a3.png)

### Actual behavior

```
kando@benvolio ~ % brew tap microsoft/git             
==> Tapping microsoft/git
Cloning into '/opt/homebrew/Library/Taps/microsoft/homebrew-git'...
remote: Enumerating objects: 417, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 417 (delta 165), reused 154 (delta 88), pack-reused 129
Receiving objects: 100% (417/417), 96.39 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (240/240), done.
Tapped 4 casks (20 files, 124.5KB).
kando@benvolio ~ % brew install --cask git-credential-manager-core
==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://github.com/GitCredentialManager/git-credential-manager/r
==> Downloading from https://objects.githubusercontent.com/github-production-rel
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'git-credential-manager-core' with message: Download failed: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.931/gcm-osx-arm64-2.0.931.pkg
kando@benvolio ~ % brew install git-credential-manager
==> Downloading https://formulae.brew.sh/api/formula.jws.json

Error: git-credential-manager has been disabled because it has an archived upstream repository!
```

**Comment by itskando** [comment] 2023-02-27 20:53
https://formulae.brew.sh/formula/git-credential-manager#default 

refers to git-credential-manager rather than git-credential-manager-core

There is no `git-credential-manager-core` in the homebrew catalog.

Using `brew install git-credential-manager-core` worked without `--cask`.  
(Re)installations with `--cask` worked after this, for whatever reason.

**Comment by trinitykey** [comment] 2023-02-27 21:12
_macOS Ventura 13.2.1_

I'm having a similar error while trying to run `brew install git-credential-manager-core`. This is the output I'm receiving: 


```==> Purging files for version 2.0.931 of Cask git-credential-manager-core
Error: Failure while executing; `/usr/bin/sudo -E LOGNAME=XXXXXX USER=XXXXXX USERNAME=XXXXXX -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/git-credential-manager-core/2.0.931/gcm-osx-arm64-2.0.931.pkg -target / -allowUntrusted` exited with 1. Here's the output:
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcm-osx-arm64-2.0.931.pkg”.)```

**Comment by ldennington** [comment] 2023-02-27 21:51
@trinitykey - that is a known issue. See #1035.

@itskando - GCM should not be in the Homebrew catalog, as it's published from a private tap. The `git-credential-manager` that you're seeing is the predecessor of GCM which is now deprecated (hence the red circle with line through it).

It is odd that you saw that 404 when attempting your install. Just to make sure everything worked as expected, can you paste in the output you see when you run `git-credential-manager --version`?

**Comment by itskando** [comment] 2023-02-27 21:57
> Can you paste in the output you see when you run `git-credential-manager --version`?

2.0.931+f99d745b98

**Comment by ldennington** [comment] 2023-02-27 22:21
Ok, that is the latest version, so you should be good to go. We think this may have been a transient network failure - we are unable to reproduce, so going to go ahead and close this issue.

**Closed by ldennington** 2023-02-27 22:21 UTC
Labels: auth-issue

**Comment by Anton2686** [comment] 2023-03-09 01:26
@itskando
