### ISSUE TITLE
TortoiseGit warnings showing suddenly for the last few days: failed to probe 'https://gitlab.com/' to detect provider

### ISSUE THREAD

**Issue by Mugane** [GitCredentialManager/git-credential-manager#632] opened 2022-03-14 06:37 UTC
This is happening when I do git clone via TortoiseGit v2.12.0.0

Git Credential Manager version 2.0.632+478753bbb7 (Windows 7 Ultimate, .NET Core 4.8.03761)

Works in browser, works using TortoiseGit, just returns a bunch of new warnings. 

`git remote -v` returns the repo url https://gitlab.com/[redacted]/[redacted].git

**Expected behavior**

git clone pulls repo and no warnings are generated.

**Actual behavior**

The repo is cloned but I get a bunch of warnings that I never got before last week:

```
$ git clone https://gitlab.com/[redacted]/[redacted].git
Cloning into '[redacted]'...
warning: failed to probe 'https://gitlab.com/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
warning: failed to probe 'https://gitlab.com/' to detect provider
warning: An error occurred while sending the request.
warning: see https://aka.ms/gcm/autodetect for more information.
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 42 (delta 19), reused 34 (delta 14), pack-reused 0
Receiving objects: 100% (42/42), 29.21 KiB | 7.30 MiB/s, done.
Resolving deltas: 100% (19/19), done.
```

**Comment by mjcheetham** [comment] 2022-03-14 16:01
Hi @Mugane, thanks for reporting this.

These are warning messages indicating GCM is unable to reach gitlab.com to determine some configuration. You might be able to see what the problem is by running the following in a PowerShell window:

```powershell
Invoke-WebRequest -Uri "https://gitlab.com" -Method Head
```

> Git Credential Manager version 2.0.632+478753bbb7 (Windows 7 Ultimate, .NET Core 4.8.03761)

However, I suspect the problem may be TLS related. Windows 7 does not support TLS 1.2 by default. The best solution to that is to upgrade to a newer version of Windows. Alternatively you can try [enabling TLS 1.2 on older versions of Windows](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2) by following Microsoft's instructions here: https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client

You should also be able to disable these GCM warning messages by running the following in a command prompt window:

```
git config --global credential.gitlab.com.provider generic
```

**Comment by Mugane** [comment] 2022-03-14 23:23
Thanks @mjcheetham! Indeed, `Invoke-WebRequest` returned some more details (below). I'll do the TLS updates a little later and post outcome here for future reference. 

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\[redacted]> Invoke-WebRequest -Uri "https://gitlab.com" -Method Head
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri "https://gitlab.com" -Method Head
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by ldennington** [comment] 2022-03-30 14:54
Closing this out for now. @Mugane - if the update didn't fix your issue, please feel free to ask here again.

**Closed by ldennington** 2022-03-30 14:54 UTC
Labels: auth-issue
